---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: stefanpeng
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: stefanpeng
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: use caps lock as ctrl
    become_user: stefanpeng
    dconf:
      key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:ctrl_modifier']"

  - name: enable night light
    dconf:
      key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"

  - name: enable rgb antialiasing
    dconf:
      key: "org/gnome/settings-daemon/plugins/xsettings/antialiasing"
      value: "'RGB'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/stefanpeng/.bashrc
      owner: stefanpeng
      group: stefanpeng

  - name: copy .vimrc file
    copy:
      src: files/vimrc
      dest: /home/stefanpeng/.vimrc
      owner: stefanpeng
      group: stefanpeng

  - name: add ansible user
    user:
      name: ansie
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansie
      dest: /etc/sudoers.d/ansie
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansie
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/stefan-peng/ansible_desktop.git
