---
- hosts: localhost
  connection: local
  become: true

  tasks:
      
  - name: install packages
    package:
      name:
        - gdb
        - valgrind
        - htop
        - tmux
        - vim-nox
        - python3-psutil
        - thunderbird
        - gnome-tweaks
        - mpv
        - yt-dlp


  - name: enable flathub repository
    become: yes
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: install steam
    become: yes
    command: flatpak install --assumeyes flathub com.valvesoftware.Steam

  - name: install lutris
    become: yes
    command: flatpak install --assumeyes flathub net.lutris.Lutris

  - name: install lollypop
    become: yes
    command: flatpak install --assumeyes flathub org.gnome.Lollypop

  - name: install foliate
    become: yes
    command: flatpak install --assumeyes flathub com.github.johnfactotum.Foliate

  - name: enable MOZ_USE_XINPUT2
    copy:
      src: files/use-xinput2.sh
      dest: /etc/profile.d/use-xinput2.sh
      owner: root
      group: root

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: speng
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper
    become_user: speng
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: speng
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: use caps lock as ctrl
    become_user: speng
    dconf:
      key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:ctrl_modifier']"

  - name: enable night light
    become_user: speng
    dconf:
      key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"

  - name: enable rgb antialiasing
    become_user: speng
    dconf:
      key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing"
      value: "'rgba'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/speng/.bashrc
      owner: speng
      group: speng

  - name: copy .vimrc file
    copy:
      src: files/vimrc
      dest: /home/speng/.vimrc
      owner: speng
      group: speng

  - name: copy .gitconfig file
    copy:
      src: files/gitconfig
      dest: /home/speng/.gitconfig
      owner: speng
      group: speng

  - name: copy mpv config
    synchronize:
      src: files/mpv/
      dest: /home/speng/.config/mpv/
      
  - name: add ansible user
    user:
      name: ansie
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansie
      dest: /etc/sudoers.d/ansie
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansie
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/stefan-peng/ansible_desktop.git
